# Generated by Django 4.0.3 on 2022-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default='')),
                ('stock', models.CharField(default='', max_length=255)),
                ('image_link', models.CharField(max_length=2083)),
            ],
        ),
    ]
