# Generated by Django 4.0.3 on 2022-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='hi', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default='1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.CharField(default='7', max_length=255),
        ),
    ]
